bugfix: request headers contains "_" should be case-insensitive matched.
openresty/lua-resty-core pull request #419
Opened 2023-02-17 07:37 UTC by vm-001

2023-02-17 08:03 UTC, zhuizhuhaomeng approved these changes

2023-02-17 08:04 UTC, zhuizhuhaomeng commented
@vm-001 you have removed spaces that should not be removed

2023-02-17 08:19 UTC, vm-001 commented
@zhuizhuhaomeng Ops, Looks like the IntelliJ IDEA is not intelligent at this moment. Fixed.

2023-02-20 12:17 UTC, vm-001 commented
@zhuizhuhaomeng I think the CI failure is not caused by the PR because I also found a similar failure in another empty PR(https://app.travis-ci.com/github/openresty/lua-resty-core/builds/260795767)

2023-02-21 01:12 UTC, zhuizhuhaomeng requested changes

2023-02-21 01:12 UTC, zhuizhuhaomeng commented on t/request.t
> +}
```suggestion
--- http_config
    underscores_in_headers on;
```

2023-03-07 03:28 UTC, vm-001 commented
Hi @zhuizhuhaomeng , May I know can this PR be merged?

2023-03-07 07:21 UTC, zhuizhuhaomeng commented
@vm-001 
The CI ran failed.
Please rebase to the latest master branch code.

2023-03-09 02:47 UTC, zhuizhuhaomeng commented
https://app.travis-ci.com/github/openresty/lua-resty-core/builds/261234448#L575
The CI failed. Please have a look at this one.

2023-03-09 06:14 UTC, vm-001 commented
> https://app.travis-ci.com/github/openresty/lua-resty-core/builds/261234448#L575 The CI failed. Please have a look at this one.

Thanks for the reminder. I've fixed the test fails. But I saw the CI still fails, have no idea what's wrong.

2023-03-15 06:14 UTC, vm-001 commented
@zhuizhuhaomeng Haven't received any reply for a while. Is it ready to merge?

2023-03-15 15:06 UTC, zhuizhuhaomeng requested changes

2023-03-15 15:06 UTC, zhuizhuhaomeng commented on lib/resty/core/request.lua
> +            value =  rawget(tb, (str_replace_char(key, '_', '-')))
```suggestion
            if value == nil and str_find(key, '_', 1, true) then
```

2023-03-15 15:06 UTC, zhuizhuhaomeng commented on lib/resty/core/request.lua
> +            value =  rawget(tb, (str_replace_char(key, '_', '-')))
this is a bit faster.

2023-03-16 02:29 UTC, vm-001 commented on lib/resty/core/request.lua
> +        end
```suggestion
        if value == nil and str_find(key, '_', 1, true) then
            value =  rawget(tb, (str_replace_char(key, '_', '-')))
        end
```

2023-03-16 02:30 UTC, zhuizhuhaomeng commented
This is still needed.
```
value = rawget(tb, (str_replace_char(key, '_', '-')))
```

2023-03-16 02:33 UTC, vm-001 commented
@zhuizhuhaomeng Yeah. I found the suggestion applied on the wrong line. I've made another suggestion to correct that.

2023-03-20 09:45 UTC, merged